src/IsotopeOrdering.UI/Controllers/CustomerController.cs
using IsotopeOrdering.App;
using IsotopeOrdering.App.Interfaces;
using IsotopeOrdering.App.Models.Details;
using IsotopeOrdering.App.Models.Items;
using IsotopeOrdering.App.Models.Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace IsotopeOrdering.UI.Controllers {
    [Authorize(Policies.PrivatePolicy)]
    public class CustomerController : BaseController {
        private readonly ICustomerManager _customerManager;

        public CustomerController(ICustomerManager customerManager) {
            _customerManager = customerManager;
        }

        [HttpGet]
        [Authorize(Policies.ReviewerPolicy)]
        public async Task<IActionResult> Manage() {
            return View(await _customerManager.GetList());
        } 

        [HttpGet]
        [Authorize(Policies.CustomerPolicy)]
        public async Task<IActionResult> MyTeam() {
            return View(await _customerManager.GetList());
        }

        [HttpGet]
        [Authorize(Policies.CustomerPolicy)]
        public async Task<IActionResult> MyProfile() {
            CustomerItemModel? customer = await _customerManager.GetCurrentCustomer();
            if (customer == null) {
                return NotFound();
            }
            CustomerDetailModel? model = await _customerManager.Get(customer.Id);
            if (model == null) {
                return NotFound();
            }
            return View(model);
        }

        [HttpPost]
        [Authorize(Policies.CustomerPolicy)]
        public async Task<IActionResult> MyProfile(CustomerDetailModel model) {
            if (ModelState.IsValid) {
                ApplicationResult result = await _customerManager.Edit(model);
                SetApplicationResult(result);
                return RedirectToAction(nameof(MyProfile));
            }
            return View(model);
        }

        [HttpGet]
        [Authorize(Policies.ReviewerPolicy)]
        public async Task<IActionResult> Edit(int id) {
            CustomerDetailModel? model = await _customerManager.Get(id);
            if (model == null) {
                return NotFound();
            }
            return View(model);
        }

        [HttpGet]
        [Authorize(Policies.ReviewerPolicy)]
        public async Task<IActionResult> Search(string search) {
            return Json(await _customerManager.Search(search));
        }

        [HttpPost]
        [Authorize(Policies.ReviewerPolicy)]
        public async Task<IActionResult> Edit(CustomerDetailModel model) {
            if (ModelState.IsValid) {
                ApplicationResult result = await _customerManager.Edit(model);
                SetApplicationResult(result);
                return RedirectToAction(nameof(Edit), new { id = model.Id });
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddCustomerAddress(CustomerAddressDetailModel model) => await Partial("_CustomerAddress", model);

        [HttpPost]
        public async Task<IActionResult> AddCustomerInstituion(CustomerInstitutionDetailModel model) => await Partial("_CustomerInstitution", model);

        [HttpPost]
        public async Task<IActionResult> AddCustomerDocument(CustomerDocumentDetailModel model) => await Partial("_CustomerDocument", model);

        [HttpPost]
        public async Task<IActionResult> AddCustomerItem(ItemConfigurationDetailModel model) => await Partial("_CustomerItem", model);
    }
}

src/IsotopeOrdering.UI/Controllers/FormController.cs
using IsotopeOrdering.App;
using IsotopeOrdering.App.Interfaces;
using IsotopeOrdering.App.Models.Details;
using IsotopeOrdering.App.Models.Items;
using IsotopeOrdering.App.Models.Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace IsotopeOrdering.UI.Controllers {
    public class FormController : BaseController {
        private readonly IFormManager _formManager;
        private readonly ICustomerManager _customerManager;

        public FormController(IFormManager formManager, ICustomerManager customerManager) {
            _formManager = formManager;
            _customerManager = customerManager;
        }

        [HttpGet]
        [Authorize(Policies.PrivatePolicy)]
        public async Task<IActionResult> InitiationForm() {
            CustomerItemModel? customer = await _customerManager.GetCurrentCustomer(); 
            if (customer == null) {
                return NotFound();
            }
            return View(await _formManager.GetInitiationForm(customer));
        }

        [HttpGet]
        [Authorize(Policies.PrivatePolicy)]
        [Route("Form/InitiationForm/{customerFormId}")]
        public async Task<IActionResult> InitiationForm(int customerFormId) {
            FormDetailModel? form = await _formManager.GetInitiationForm(customerFormId);
            if (form == null) {
                return NotFound();
            }
            return View(form);
        }

        [HttpGet]
        [Authorize(Policies.PublicPolicy)]
        [Route("Form/InitiationForm/{supervisorEmailAddress}/{formIdentifier}")]
        public async Task<IActionResult> InitiationForm(string supervisorEmailAddress, Guid formIdentifier) {
            FormDetailModel? form = await _formManager.GetInitiationForm(supervisorEmailAddress, formIdentifier);
            if (form == null) {
                return NotFound();
            }
            form.AllowSignatureFromCustomerAdmin = true;
            return View(form);
        }

        [HttpPost]
        [Authorize(Policies.PublicPolicy)]
        [Route("Form/InitiationForm/{supervisorEmailAddress}/{formIdentifier}")]
        public async Task<IActionResult> InitiationForm(string supervisorEmailAddress, Guid formIdentifier, FormDetailModel model) {
            if (ModelState.IsValid) {
                ApplicationResult result = await _formManager.SubmitInitiationFormSignature(supervisorEmailAddress, formIdentifier, model.InitiationModel!.CustomerAdminSignature);
                SetApplicationResult(result);
                return RedirectToAction(nameof(HomeController.Confirmation), "Home");
            }
            model.AllowSignatureFromCustomerAdmin = true;
            return View(model);
        }

        [HttpPost]
        [Authorize(Policies.PrivatePolicy)]
        public async Task<IActionResult> InitiationForm(FormDetailModel model) {
            if (ModelState.IsValid) {
                ApplicationResult result = await _formManager.SubmitInitiationForm(model);
                SetApplicationResult(result);
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
            return View(model);
        }

    }


}

src/IsotopeOrdering.UI/Views/Customer/Manage.cshtml
@model List<CustomerItemModel>
@{
    ViewData[ViewDataKeys.Title] = "Manage Customers";
}
<partial name="_CustomerList" model="Model"/>

src/IsotopeOrdering.UI/Views/Customer/MyProfile.cshtml
@inject IConfiguration Configuration
@model CustomerDetailModel
@{
    ViewData[ViewDataKeys.Title] = "My Profile";
}

<form asp-action="@nameof(CustomerController.MyProfile)" asp-controller="Customer" method="post">
    <partial name="_CustomerForm" for="@Model" />
</form>
@section Scripts{
    <script type="text/javascript" src="@Configuration["FileUploadUri"]"></script>
    <script src="~/js/customer.js"></script>
}

src/IsotopeOrdering.UI/Views/Customer/_CustomerAddressList.cshtml
@model List<CustomerAddressDetailModel>
<ul class="list-group" id="customer-address-list">
    <partial name="_CustomerAddressAdd" model="new CustomerAddressDetailModel()"/>
    @foreach (var address in Model) {
        <partial name="_CustomerAddress" model="address" />
    }
</ul>

src/IsotopeOrdering.UI/Views/Customer/_CustomerDocument.cshtml
@model CustomerDocumentDetailModel
<li class="list-group-item m-3">
    @using (Html.BeginCollectionItem("Documents")) {
        <button type="button" class="btn btn-sm btn-danger collection-remove float-right" onclick="removeCollectionItem(this);" data-for=".list-group-item"><i class="fas fa-trash-alt"></i></button>
        <partial name="_AuditInformation" for="@Model" />
        <input type="hidden" asp-for="CustomerId" />
        <div class="form-row">
            <div class="form-group col-6">
                <label asp-for="ExpirationDate">Expiration Date</label>
                <input asp-for="ExpirationDate" class="form-control form-control-sm" type="date" />
            </div>
            <partial name="_Document" for="Document" view-data="new ViewDataDictionary(ViewData) { { ViewDataKeys.UploadModule,UploadModules.CustomerDocument},{ ViewDataKeys.Readonly,bool.TrueString} }" />
        </div>
    }
</li>

src/IsotopeOrdering.UI/Views/Customer/_CustomerDocumentAdd.cshtml
@model CustomerDocumentDetailModel
<li class="list-group-item border-info m-3 add-collection-item">
    <div class="col-sm-12 col-md-6 pl-0">
        <label asp-for="ExpirationDate">Expiration Date</label>
        <input asp-for="ExpirationDate" class="form-control form-control-sm" type="date" />
    </div>
    <partial name="_Document" model="new DocumentDetailModel()" view-data="new ViewDataDictionary(ViewData) { { ViewDataKeys.UploadModule,UploadModules.CustomerDocument} }" />
    <button type="button" class="btn btn-sm btn-success" onclick="addCustomerDocument(this)" data-url="@Url.Action(nameof(CustomerController.AddCustomerDocument))" data-target="#customer-document-list">Add New Document</button>
</li>

src/IsotopeOrdering.UI/Views/Customer/_CustomerFormAdmin.cshtml
@model CustomerDetailModel
    <div class="mr-3 ml-3 p-4">
        <div class="form-group">
            <label asp-for="Status">Status</label>
            <select asp-for="Status" asp-items="ListUtility.GetCustomerStatuses()" class="form-control form-control-sm"></select>
            <span asp-validation-for="Status" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="InternalNotes">Internal Notes</label>
            <textarea asp-for="InternalNotes" class="form-control form-control-sm"></textarea>
            <span asp-validation-for="InternalNotes" class="text-danger"></span>
        </div>
    </div>
<partial name="_CustomerItemList" for="ItemConfigurations" />

src/IsotopeOrdering.UI/Views/Customer/_CustomerFormList.cshtml
@model List<FormItemModel>

<div class="table-responsive table-fadein mt-3">
    <table class="table table-hover table-bordered table-sm table-datatable">
        <thead>
            <tr>
                <th>Name</th>
                <th>Form Type</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {
                <tr class="clickable" onclick="window.location='@Url.Action(nameof(FormController.InitiationForm),"Form",new { id = item.CustomerDetailFormId})'">
                    <td>@item.Name</td>
                    <td>@item.Type.ToString()</td>
                    <td>@item.Status.ToString()</td>
                </tr>
            }
        </tbody>
    </table>
</div>

src/IsotopeOrdering.UI/Views/Customer/_CustomerInstitution.cshtml
@model CustomerInstitutionDetailModel
    <li class="list-group-item m-3">
        @using (Html.BeginCollectionItem("Institutions")) {
            <button type="button" class="btn btn-sm btn-danger collection-remove float-right" onclick="removeCollectionItem(this);" data-for=".list-group-item"><i class="fas fa-trash-alt"></i></button>
            <partial name="_AuditInformation" for="@Model" />
            <input type="hidden" asp-for="CustomerId" />
            <input type="hidden" asp-for="InstitutionId" />
            <partial name="_Institution" for="Institution" />
        }
    </li>

src/IsotopeOrdering.UI/Views/Customer/_CustomerInstitutionAdd.cshtml
@model CustomerInstitutionDetailModel
<li class="list-group-item border-info m-3 add-collection-item">
    <partial name="_Institution" model="new InstitutionDetailModel()" />
    <button type="button" class="btn btn-sm btn-success" onclick="addCustomerInstitution(this)" data-url="@Url.Action(nameof(CustomerController.AddCustomerInstituion))" data-target="#customer-institution-list">Add New Institution</button>
</li>

src/IsotopeOrdering.UI/Views/Customer/_CustomerInstitutionList.cshtml
@model List<CustomerInstitutionDetailModel>
<ul class="list-group" id="customer-institution-list">
    <partial name="_CustomerInstitutionAdd" model="new CustomerInstitutionDetailModel()" />
    @foreach (var institution in Model) {
        <partial name="_CustomerInstitution" model="institution" />
    }
</ul>

src/IsotopeOrdering.UI/Views/Customer/_CustomerItem.cshtml
@model ItemConfigurationDetailModel
    <li class="list-group-item m-3">
        @using (Html.BeginCollectionItem("ItemConfigurations")) {

            <input type="hidden" asp-for="ItemId" />
            <input type="hidden" asp-for="CustomerId" />
            <partial name="_AuditInformation" for="@Model" />
            <div class="form-row">
                <div class="col">
                    <label asp-for="ItemName">Material</label>
                    <input type="text" readonly="readonly" asp-for="ItemName" class="form-control form-control-sm" />
                </div>
                <div class="col">
                    <label asp-for="Price"></label>
                    <div class="input-group input-group-sm">
                        <div class="input-group-prepend">
                            <div class="input-group-text">$</div>
                        </div>
                        <input type="number" readonly="readonly" asp-for="Price" class="form-control form-control-sm" />
                    </div>
                </div>
                <div class="col">
                    <label asp-for="MinimumAmount">Minimum Amount</label>
                    <input type="number" readonly="readonly" asp-for="MinimumAmount" class="form-control form-control-sm" />
                </div>
                <div class="col">
                    <label asp-for="MaximumAmount">Maximum Amount</label>
                    <input type="number" readonly="readonly" asp-for="MaximumAmount" class="form-control form-control-sm" />
                </div>
                <div class="col-auto">
                    <button type="button" class="btn btn-sm btn-danger" onclick="removeCollectionItem(this);" data-for=".list-group-item"><i class="fas fa-trash-alt"></i></button>
                </div>
            </div>
            
        }
    </li>

src/IsotopeOrdering.UI/Views/Customer/_CustomerItemAdd.cshtml
@inject IItemManager ItemManager
@model ItemConfigurationDetailModel
<li class="list-group-item border-info m-3 add-item-item">
    <div class="form-row">
        <div class="col">
            <label asp-for="ItemId">Material</label>
            <select asp-for="ItemId" asp-items="@new SelectList(await ItemManager.GetList(),nameof(ItemItemModel.Id),nameof(ItemItemModel.Name))" class="form-control form-control-sm"></select>
            <span asp-validation-for="ItemId" class="text-danger"></span>
        </div>
        <div class="col">
            <label asp-for="Price"></label>
            <div class="input-group input-group-sm">
                <div class="input-group-prepend">
                    <div class="input-group-text">$</div>
                </div>
                <input type="number" asp-for="Price" class="form-control form-control-sm" />
            </div>
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div class="col">
            <label asp-for="MinimumAmount">Minimum Amount</label>
            <input type="number" asp-for="MinimumAmount" class="form-control form-control-sm" />
        </div>
        <div class="col">
            <label asp-for="MaximumAmount">Maximum Amount</label>
            <input type="number" asp-for="MaximumAmount" class="form-control form-control-sm" />
        </div>
    </div>
    <button type="button" class="btn btn-sm btn-sm btn-success mt-5" onclick="addCustomerItem(this)" data-url="@Url.Action(nameof(CustomerController.AddCustomerItem))" data-target="#customer-item-list">Add New Material Configuration</button>
</li>

src/IsotopeOrdering.UI/Views/Customer/_CustomerSubscription.cshtml
@model CustomerSubscriptionDetailModel

@using (Html.BeginCollectionItem("SubscriptionConfiguration.Subscriptions")) {
    <div class="custom-control custom-switch">
        <partial name="_AuditInformation" for="@Model" />
        @if (Model.IsSelected) {
            <input type="checkbox" class="custom-control-input" asp-for="IsSelected" checked="checked">
        }
        else {
        <input type="checkbox" class="custom-control-input" asp-for="IsSelected" >
        }
        <label class="custom-control-label" asp-for="IsSelected">@Model.Configuration.Title</label>
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="CustomerId" />
        <input type="hidden" asp-for="Configuration.Id" />
    </div>
}

src/IsotopeOrdering.UI/Views/Customer/_CustomerSubscriptionList.cshtml
@model CustomerSubscriptionConfigurationModel
@for (var i = 0; i < Model.NotificationConfigurations.Count; i++) {
    NotificationConfigurationItemModel configuration = Model.NotificationConfigurations[i];
    CustomerSubscriptionDetailModel subscription = Model.Subscriptions.SingleOrDefault(x => x.Configuration.Id == configuration.Id);
    if (subscription == null) {
        subscription = new CustomerSubscriptionDetailModel(configuration);
    }
    <partial name="_CustomerSubscription" model="subscription" />
}