src/IsotopeOrdering.UI/Controllers/CustomerController.cs
using IsotopeOrdering.App;
using IsotopeOrdering.App.Interfaces;
using IsotopeOrdering.App.Models.Details;
using IsotopeOrdering.App.Models.Items;
using IsotopeOrdering.App.Models.Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace IsotopeOrdering.UI.Controllers {
    [Authorize(Policies.PrivatePolicy)]
    public class CustomerController : BaseController {
        private readonly ICustomerManager _customerManager;

        public CustomerController(ICustomerManager customerManager) {
            _customerManager = customerManager;
        }

        [HttpGet]
        [Authorize(Policies.ReviewerPolicy)]
        public async Task<IActionResult> Manage() {
            return View(await _customerManager.GetList());
        } 

        [HttpGet]
        [Authorize(Policies.CustomerPolicy)]
        public async Task<IActionResult> MyTeam() {
            return View(await _customerManager.GetList());
        }

        [HttpGet]
        [Authorize(Policies.CustomerPolicy)]
        public async Task<IActionResult> MyProfile() {
            CustomerItemModel? customer = await _customerManager.GetCurrentCustomer();
            if (customer == null) {
                return NotFound();
            }
            CustomerDetailModel? model = await _customerManager.Get(customer.Id);
            if (model == null) {
                return NotFound();
            }
            return View(model);
        }

        [HttpPost]
        [Authorize(Policies.CustomerPolicy)]
        public async Task<IActionResult> MyProfile(CustomerDetailModel model) {
            if (ModelState.IsValid) {
                ApplicationResult result = await _customerManager.Edit(model);
                SetApplicationResult(result);
                return RedirectToAction(nameof(MyProfile));
            }
            return View(model);
        }

        [HttpGet]
        [Authorize(Policies.ReviewerPolicy)]
        public async Task<IActionResult> Edit(int id) {
            CustomerDetailModel? model = await _customerManager.Get(id);
            if (model == null) {
                return NotFound();
            }
            return View(model);
        }

        [HttpGet]
        [Authorize(Policies.ReviewerPolicy)]
        public async Task<IActionResult> Search(string search) {
            return Json(await _customerManager.Search(search));
        }

        [HttpPost]
        [Authorize(Policies.ReviewerPolicy)]
        public async Task<IActionResult> Edit(CustomerDetailModel model) {
            if (ModelState.IsValid) {
                ApplicationResult result = await _customerManager.Edit(model);
                SetApplicationResult(result);
                return RedirectToAction(nameof(Edit), new { id = model.Id });
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddCustomerAddress(CustomerAddressDetailModel model) => await Partial("_CustomerAddress", model);

        [HttpPost]
        public async Task<IActionResult> AddCustomerInstituion(CustomerInstitutionDetailModel model) => await Partial("_CustomerInstitution", model);

        [HttpPost]
        public async Task<IActionResult> AddCustomerDocument(CustomerDocumentDetailModel model) => await Partial("_CustomerDocument", model);

        [HttpPost]
        public async Task<IActionResult> AddCustomerItem(ItemConfigurationDetailModel model) => await Partial("_CustomerItem", model);
    }
}

src/IsotopeOrdering.UI/Controllers/ItemController.cs
using IsotopeOrdering.App;
using IsotopeOrdering.App.Interfaces;
using IsotopeOrdering.App.Models.Details;
using IsotopeOrdering.App.Models.Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace IsotopeOrdering.UI.Controllers {

    [Authorize(Policies.AdminPolicy)]
    public class ItemController : BaseController {
        private readonly IItemManager _itemManager;

        public ItemController(IItemManager itemManager) {
            _itemManager = itemManager;
        }

        [HttpGet]
        public async Task<IActionResult> Manage() {
            return View(await _itemManager.GetList());
        }


        [HttpGet]
        public async Task<IActionResult> Create() { 
            return View(await Task.FromResult(new ItemDetailModel()));
        }

        [HttpPost]
        public async Task<IActionResult> Create(ItemDetailModel model) {
            if (ModelState.IsValid) {
                ApplicationResult result = await _itemManager.Create(model);
                SetApplicationResult(result);
                return RedirectToAction(nameof(Manage));
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id) {
            ItemDetailModel? model = await _itemManager.Get(id);
            if (model == null) {
                return NotFound();
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ItemDetailModel model) {
            if (ModelState.IsValid) {
                ApplicationResult result = await _itemManager.Edit(model);
                SetApplicationResult(result);
                return RedirectToAction(nameof(Manage));
            }
            return View(model);
        }
    }
}

src/IsotopeOrdering.UI/Views/Shared/_ApplicationResult.cshtml
@model ApplicationResult
@if (Model.IsSuccessful) {
    <div class="alert alert-success alert-dismissible fade show m-4" role="alert">
        <strong>Success</strong> @Model.Message
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}
else {
    <div class="alert alert-danger alert-dismissible fade show m-4" role="alert">
        <strong>Error</strong>@Model.Message
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

src/IsotopeOrdering.UI/Views/Shared/_AuditInformation.cshtml
@model ModelBase
<input type="hidden" asp-for="Id" />
<input type="hidden" asp-for="CreatedBy" />
<input type="hidden" asp-for="CreatedDate" />
<input type="hidden" asp-for="UpdatedBy" />
<input type="hidden" asp-for="UpdatedDate" />
<input type="hidden" asp-for="IsDeleted" />

src/IsotopeOrdering.UI/Views/Shared/_AuditInformationView.cshtml
@model ModelBase
<span>@($"Created By:{Model.CreatedBy} {Model.CreatedDate.ToString()}|Updated By:{Model.UpdatedBy} {Model.UpdatedDate.ToString()}")</span>

src/IsotopeOrdering.UI/Views/Shared/_Contact.cshtml
@model ContactDetailModel

@if (ViewData.IsReadonly()) {
    <div class="form-row">
        <div class="form-group col-4">
            <label asp-for="FirstName">First Name</label>
            <input asp-for="FirstName" class="form-control form-control-sm" readonly/>
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="form-group col-4">
            <label asp-for="LastName">Last Name</label>
            <input asp-for="LastName" class="form-control form-control-sm" readonly/>
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="form-group col-4">
            <label asp-for="Email">Email</label>
            <input asp-for="Email" class="form-control form-control-sm" readonly/>
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-4">
            <label asp-for="PhoneNumber">Phone Number</label>
            <input asp-for="PhoneNumber" class="form-control form-control-sm" readonly/>
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <div class="form-group col-4">
            <label asp-for="Fax">Fax</label>
            <input asp-for="Fax" class="form-control form-control-sm" readonly/>
            <span asp-validation-for="Fax" class="text-danger"></span>
        </div>
    </div>
}
else {
    <div class="form-row">
        <div class="form-group col-4">
            <label asp-for="FirstName">First Name</label>
            <input asp-for="FirstName" class="form-control form-control-sm" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="form-group col-4">
            <label asp-for="LastName">Last Name</label>
            <input asp-for="LastName" class="form-control form-control-sm" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="form-group col-4">
            <label asp-for="Email">Email</label>
            <input asp-for="Email" class="form-control form-control-sm" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-4">
            <label asp-for="PhoneNumber">Phone Number</label>
            <input asp-for="PhoneNumber" class="form-control form-control-sm" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <div class="form-group col-4">
            <label asp-for="Fax">Fax</label>
            <input asp-for="Fax" class="form-control form-control-sm" />
            <span asp-validation-for="Fax" class="text-danger"></span>
        </div>
    </div>
}

src/IsotopeOrdering.UI/Views/Shared/_Document.cshtml
@model DocumentDetailModel
<input type="hidden" asp-for="UploadId" />
<div class="row">
    @if (ViewData.IsReadonly()) {
        <div class="col-sm-12 col-md-6">
            <div class="form-group">
                <label asp-for="Name">Document Name</label>
                <input asp-for="Name" class="form-control form-control-sm" readonly />
                
            </div>
            <div class="form-group">
                <label asp-for="Details">Details</label>
                <textarea asp-for="Details" class="form-control form-control-sm" rows="3" readonly></textarea>
            </div>
        </div>
    }
    else {
        <div class="col-sm-12 col-md-6">
            <div class="form-group">
                <label asp-for="Name">Document Name</label>
                <input asp-for="Name" class="form-control form-control-sm" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Details">Details</label>
                <textarea asp-for="Details" class="form-control form-control-sm" rows="3"></textarea>
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
        </div>
    }
    <div class="form-group col-sm-12 col-md-6" style="min-height:175px;">
        <label>Files</label>
        @if (ViewData[ViewDataKeys.Readonly] == null) {
            <div class="document-upload" data-module="@ViewData[ViewDataKeys.UploadModule]" data-entityid="@Model.UploadId.ToString()"></div>
        }
        else {
            <div class="document-upload" data-module="@ViewData[ViewDataKeys.UploadModule]" data-entityid="@Model.UploadId.ToString()" data-readonly="@ViewData[ViewDataKeys.Readonly]"></div>
        }
    </div>
</div>

src/IsotopeOrdering.UI/Views/Shared/_Institution.cshtml
@model InstitutionDetailModel
<partial name="_AuditInformation" />
@if (ViewData.IsReadonly()) {
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="Name">Institution Name</label>
        <div class="col-sm-10">
            <input asp-for="Name" class="form-control form-control-sm" readonly />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <h6 class="mb-2 text-muted"><i class="fas fa-home pr-1"></i>Institution Address</h6>
    <partial name="_Address" for="Address" />
    <div class="row">
        <div class="col-6">
            <h6 class="mb-2 text-muted"><i class="fas fa-id-card pr-1"></i>Safety Contact Information</h6>
            <partial name="_Contact" for="SafetyContact" />
        </div>
        <div class="col-6">
            <h6 class="mb-2 text-muted"><i class="fas fa-id-card pr-1"></i>Financial Contact Information</h6>
            <partial name="_Contact" for="FinancialContact" />
        </div>
    </div>
}
else {
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="Name">Institution Name</label>
        <div class="col-sm-10">
            <input asp-for="Name" class="form-control form-control-sm" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <h6 class="mb-2 text-muted"><i class="fas fa-home pr-1"></i>Institution Address</h6>
    <partial name="_Address" for="Address" />
    <div class="row">
        <div class="col-6">
            <h6 class="mb-2 text-muted"><i class="fas fa-id-card pr-1"></i>Safety Contact Information</h6>
            <partial name="_Contact" for="SafetyContact" />
        </div>
        <div class="col-6">
            <h6 class="mb-2 text-muted"><i class="fas fa-id-card pr-1"></i>Financial Contact Information</h6>
            <partial name="_Contact" for="FinancialContact" />
        </div>
    </div>
}

src/IsotopeOrdering.UI/Views/Shared/_ItemConfigurationList.cshtml
@model List<ItemConfigurationDetailModel>
@foreach(var itemConfiguration in Model) {
    <partial name="_ItemConfigurationView" model="itemConfiguration"/>
}

src/IsotopeOrdering.UI/Views/Shared/_ItemConfigurationView.cshtml
@model ItemConfigurationDetailModel
<partial name="_AuditInformation" for="@Model" />
<div class="form-row border rounded mb-1">
    @if (Model.MinimumAmount.HasValue) {
        <div class="col-sm-12 col-md-4">
            <div class="form-group">
                <label asp-for="MinimumAmount">Minimum Amount Required</label>
                <input class="form-control form-control-sm" readonly="readonly" asp-for="MinimumAmount" />
            </div>
        </div>
    }
    else {
        <div class="col-sm-12 col-md-4">
            <div class="form-group">
                <label asp-for="MinimumAmount">Minimum Amount Required</label>
                <input class="form-control form-control-sm" readonly="readonly" value="N/A">
            </div>
        </div>
    }
    @if (Model.MaximumAmount.HasValue) {
        <div class="col-sm-12 col-md-4">
            <div class="form-group">
                <label asp-for="MaximumAmount">Maximum Amount Allowed</label>
                <input class="form-control form-control-sm" readonly="readonly" asp-for="MaximumAmount" />
            </div>
        </div>
    }
    else {
        <div class="col-sm-12 col-md-4">
            <div class="form-group">
                <label asp-for="MaximumAmount">Maximum Amount Allowed</label>
                <input class="form-control form-control-sm" readonly="readonly" value="N/A">
            </div>
        </div>
    }
    <div class="col-sm-12 col-md-4">
        <div class="form-group">
            <label asp-for="Price"></label>
            <div class="input-group input-group-sm">
                <div class="input-group-prepend">
                    <div class="input-group-text">$</div>
                </div>
                <input type="number" readonly="readonly" asp-for="Price" class="form-control form-control-sm" />
            </div>
        </div>
    </div>
</div>

src/IsotopeOrdering.UI/Views/Shared/_ItemInformation.cshtml
@model ItemDetailModel
<partial name="_AuditInformation" for="@Model" />
<div class="form-row">
    <div class="col-sm-12 col-md-3">
        <div class="form-group">
            <label asp-for="Name">Material</label>
            <input class="form-control form-control-sm" readonly asp-for="Name">
        </div>
    </div>
    <div class="col-sm-12 col-md-3">
        <div class="form-group">
            <label asp-for="Target"></label>
            <input class="form-control form-control-sm" readonly asp-for="Target">
        </div>
    </div>
    <div class="col-sm-12 col-md-3">
        <div class="form-group">
            <label asp-for="Reaction"></label>
            <input class="form-control form-control-sm" readonly asp-for="Reaction">
        </div>
    </div>
    <div class="col-sm-12 col-md-3">
        <div class="form-group">
            <label asp-for="FinalComposition">Final Composition</label>
            <input class="form-control form-control-sm" readonly asp-for="FinalComposition">
        </div>
    </div>
    @if (!string.IsNullOrEmpty(@Model.Description)) {
        <div class="col-sm-12 col-md-3">
            <div class="form-group">
                <label asp-for="Description">Description</label>
                <input class="form-control form-control-sm" readonly asp-for="Description">
            </div>
        </div>
    }
</div>

src/IsotopeOrdering.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData[ViewDataKeys.Title] - MIR - Isotope Ordering</title>
    <link rel="icon" href="~/images/wustl-icon.png" />
    <link rel="stylesheet" href="~/dist/css/datatables.min.css" />
    <link rel="stylesheet" href="~/dist/css/site.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://apps.mir.wustl.edu/MIRFileService/css/upload.css" />
</head>
<body>
    <header>
        <div class="logo-header hidden-print">
            <div class="container-fluid">
                <div class="row">
                    <img id="wusmLogo" src="~/images/wusmstl-logo-transparent-background.png" />
                    <img id="mirLogo" src="~/images/mir-logo-transparent-background.png" />
                </div>
            </div>
        </div>
        <partial name="_Nav" />
    </header>
    <div class="bs-component">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active">@ViewData[ViewDataKeys.Title]</li>
            @if (ViewData[ViewDataKeys.Info] != null) {
                <li class="breadcrumb-item"><i>@ViewData[ViewDataKeys.Info].ToString()</i></li>
            }
        </ol>

        @if (TempData.Get<ApplicationResult>(ViewDataKeys.ApplicationResult) != null) {
            <partial name="_ApplicationResult" model="TempData.Get<ApplicationResult>(ViewDataKeys.ApplicationResult)" />
        }
    </div>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer>
        <small>&copy; @DateTime.Now.Year - Mallinckrodt Institute of Radiology at Washington University School of Medicine</small>
    </footer>
    <script src="~/dist/js/jquery.min.js"></script>
    <script src="~/dist/js/datatables.min.js"></script>
    <environment include="Development">
        <script src="~/js/site.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/dist/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/IsotopeOrdering.UI/Views/Shared/_NavAdmin.cshtml
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="adminDropDown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-user-shield"></i>
        Admin
    </a>
    <div class="dropdown-menu bg-dark" aria-labelledby="adminDropDown">
        <a class="dropdown-item" asp-controller="Customer" asp-action="@nameof(CustomerController.Manage)">
            <i class="fas fa-users-cog"></i>
            Manage Customers
        </a>
        <a class="dropdown-item" asp-controller="Item" asp-action="@nameof(ItemController.Manage)">
            <i class="fa fa-flask"></i>
            Manage Items
        </a>
        @*<a class="dropdown-item" asp-controller="Report" asp-action="ArchiveReport">Manage Items</a>
        <a class="dropdown-item" asp-controller="Report" asp-action="ArchiveReport">Manage Institutions</a>*@
    </div>
</li>

src/IsotopeOrdering.UI/Views/Shared/_NavShipment.cshtml
@inject IIsotopeOrderingAuthorizationService AuthorizationService
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="orderDropDown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-truck"></i>
        Shipments
    </a>
    <div class="dropdown-menu bg-dark" aria-labelledby="orderDropDown">
        <a class="dropdown-item" asp-controller="Shipment" asp-action="@nameof(ShipmentController.MyShipments)">
            <i class="fas fa-boxes"></i>
            View My Shipments
        </a>
        @if (await AuthorizationService.AuthorizeAsync(User, Policies.ReviewerPolicy)) {
            <a class="dropdown-item" asp-controller="Shipment" asp-action="@nameof(ShipmentController.Center)">
                <i class="fas fa-warehouse"></i>
                Manage Shipments
            </a>
        }
    </div>
</li>

src/IsotopeOrdering.UI/Views/Shared/_Prompt.cshtml
<div class="modal fade" id="siteModal" tabindex="-1" role="dialog" aria-labelledby="siteModelTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="siteModelTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="submit" name="Action" class="btn btn-danger"></button>
            </div>
        </div>
    </div>
</div>

src/IsotopeOrdering.UI/Views/Shared/_RoleInfo.cshtml
@inject IRoleService RoleService
@if (RoleService.UserRoles.Any()) {
    @($"({string.Join(" - ", RoleService.UserRoles)})")
}